language: go
go:
    - 1.7.1
before_install:
    - sudo apt-get update
    - sudo apt-get install python-pygments nodejs
    - sudo ln -s nodejs /usr/bin/node
install:
    - npm install -g gulp
    - npm install
before_script:
    - go get -u -v github.com/spf13/hugo
script:
    - gulp
    - hugo
