language: ruby
rvm:
- 2.0.0
install:
- sudo apt-get update
- sudo apt-get install discount
- sudo pip install Pygments bibtex-pygments-lexer
- gem install jekyll sass rdiscount
- npm install -g clean-css yuidocjs jshint uglify-js
script: make all
