dist: trusty
sudo: required
language: go
go:
    - 1.7.3
before_install:
    - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - sudo apt-get update -qq
    - sudo apt-get install -y nodejs
    - sudo pip install pygments
install:
    - npm install -g gulp
    - npm install
before_script:
    - go get -u -v github.com/spf13/hugo
script:
    - gulp
    - hugo
