safe: false
auto: false
server: false
server_port: 4000
baseurl: /
url: https://sjp.co.nz
author: Simon Potter

source: .
destination: ./_site
plugins: ./_plugins

exclude: ["config.rb"]

future: false
lsi: false
pygments: true
markdown: rdiscount
permalink: /:categories/:title/

rdiscount:
  extensions: ["smart", "safelink"]
