safe: false
baseurl: /
url: https://sjp.co.nz
author: Simon Potter

source: .
destination: ./_site
plugins: ./_plugins

exclude: ["_config.yml", "Makefile", "rsync-remote.sh"]

future: false
lsi: false
pygments: true
markdown: rdiscount
permalink: /:categories/:title/

rdiscount:
  extensions: ["smart", "safelink"]
