safe: false
baseurl: /
url: https://sjp.co.nz
author: Simon Potter

source: .
destination: ./_site
plugins: ./_plugins

exclude: [
    "_config.yml", ".travis.yml", "Makefile", "rsync-remote.sh",
    "node_modules", "gulpfile.js", "package.json"
]

future: false
lsi: false
highlighter: pygments
markdown: rdiscount
permalink: /:categories/:title/

rdiscount:
  extensions: ["smart", "safelink"]
